# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yashm\Downloads\Project2018\gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_2.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gb_user_management = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_user_management.setObjectName("gb_user_management")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gb_user_management)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_agent_select = QtWidgets.QPushButton(self.gb_user_management)
        self.pb_agent_select.setObjectName("pb_agent_select")
        self.horizontalLayout.addWidget(self.pb_agent_select)
        self.pb_customer_select = QtWidgets.QPushButton(self.gb_user_management)
        self.pb_customer_select.setObjectName("pb_customer_select")
        self.horizontalLayout.addWidget(self.pb_customer_select)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.lbl_usertype_message = QtWidgets.QLabel(self.gb_user_management)
        self.lbl_usertype_message.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lbl_usertype_message.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.lbl_usertype_message.setText("")
        self.lbl_usertype_message.setObjectName("lbl_usertype_message")
        self.verticalLayout_3.addWidget(self.lbl_usertype_message)
        self.verticalLayout.addWidget(self.gb_user_management)
        self.gb_dialog = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_dialog.setObjectName("gb_dialog")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gb_dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tw_dialog = QtWidgets.QTabWidget(self.gb_dialog)
        self.tw_dialog.setEnabled(True)
        self.tw_dialog.setObjectName("tw_dialog")
        self.tab_agent = QtWidgets.QWidget()
        self.tab_agent.setObjectName("tab_agent")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_agent)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_agent)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pb_agent_display = QtWidgets.QPushButton(self.groupBox)
        self.pb_agent_display.setObjectName("pb_agent_display")
        self.verticalLayout_8.addWidget(self.pb_agent_display)
        self.pb_agent_add = QtWidgets.QPushButton(self.groupBox)
        self.pb_agent_add.setObjectName("pb_agent_add")
        self.verticalLayout_8.addWidget(self.pb_agent_add)
        self.pb_agent_delete = QtWidgets.QPushButton(self.groupBox)
        self.pb_agent_delete.setObjectName("pb_agent_delete")
        self.verticalLayout_8.addWidget(self.pb_agent_delete)
        self.pb_agent_search = QtWidgets.QPushButton(self.groupBox)
        self.pb_agent_search.setObjectName("pb_agent_search")
        self.verticalLayout_8.addWidget(self.pb_agent_search)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.te_agent_output = QtWidgets.QPlainTextEdit(self.tab_agent)
        self.te_agent_output.setMaximumSize(QtCore.QSize(300, 16777215))
        self.te_agent_output.setObjectName("te_agent_output")
        self.horizontalLayout_3.addWidget(self.te_agent_output)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tw_dialog.addTab(self.tab_agent, "")
        self.tab_customer = QtWidgets.QWidget()
        self.tab_customer.setObjectName("tab_customer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_customer)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tw_dialog.addTab(self.tab_customer, "")
        self.horizontalLayout_2.addWidget(self.tw_dialog)
        self.verticalLayout.addWidget(self.gb_dialog)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tw_dialog.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "DIT BOLTON STREET VEHICLE HIRE"))
        self.gb_user_management.setTitle(_translate("MainWindow", "User"))
        self.pb_agent_select.setText(_translate("MainWindow", "Agent"))
        self.pb_customer_select.setText(_translate("MainWindow", "Customer"))
        self.gb_dialog.setTitle(_translate("MainWindow", "Dialog"))
        self.tw_dialog.setToolTip(_translate("MainWindow", "Please Select a User Type"))
        self.groupBox.setTitle(_translate("MainWindow", "Agent Options"))
        self.pb_agent_display.setText(_translate("MainWindow", "Display All Vehicles"))
        self.pb_agent_add.setText(_translate("MainWindow", "Add Vehicle"))
        self.pb_agent_delete.setText(_translate("MainWindow", "Remove Vehicle"))
        self.pb_agent_search.setText(_translate("MainWindow", "Search..."))
        self.groupBox_2.setTitle(_translate("MainWindow", "Parameters"))
        self.label.setText(_translate("MainWindow", "Reg Number:"))
        self.label_3.setText(_translate("MainWindow", "Vehicle Type:"))
        self.label_4.setText(_translate("MainWindow", "Colour:"))
        self.tw_dialog.setTabText(self.tw_dialog.indexOf(self.tab_agent), _translate("MainWindow", "Agent"))
        self.tw_dialog.setTabText(self.tw_dialog.indexOf(self.tab_customer), _translate("MainWindow", "Customer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

